### PR TITLE
update OS link

### PR DESCRIPTION
**Pull request by thijstriemstra**
raspbian was renamed to raspberry pi os.

### CODE REVIEW

**Comment by thijstriemstra** [comment]
@MitchBradley could you please take a look at the open pull requests? They're simple doc fixes that would greatly benefit new cncjs users. If you need help maintaining this repository, I would gladly help. it looks like this repository ideally migrates from travis to github actions to start with..

**Comment by MitchBradley** [comment]
I am no longer active in cncjs maintenance.

**Comment by thijstriemstra** [comment]
> I am no longer active in cncjs maintenance.

I see, maybe @cheton is?

**Comment by MitchBradley** [comment]
You could look at recent activity on the main cncjs source repo to see who is active.

**Pull request closed without merging**
